FROM node:14

RUN npm install

WORKDIR /app

COPY package*.json ./

COPY . .

# Set environment variables for MongoDB and Redis connection
ENV MONGO_HOST=mongodb://mongo:27017/mydatabase
ENV REDIS_HOST=redis
ENV REDIS_PORT=6379

# Expose the port 
EXPOSE 3000

# Start the Node.js application
CMD ["node", "app.js"]